export const CATEGORIES = [
  { slug: "action", name: "Action", icon: "💥", color: "from-red-500/20 to-orange-500/20" },
  { slug: "adventure", name: "Adventure", icon: "🗺️", color: "from-blue-500/20 to-cyan-500/20" },
  { slug: "role-playing-game", name: "RPG", icon: "⚔️", color: "from-purple-500/20 to-pink-500/20" },
  { slug: "platformer", name: "Platformer", icon: "🟢", color: "from-lime-500/20 to-green-500/20" },
  { slug: "fighting", name: "Fighting", icon: "🥊", color: "from-red-500/20 to-rose-500/20" },
  { slug: "shooter", name: "Shooter", icon: "🔫", color: "from-red-500/20 to-pink-500/20" },
  { slug: "racing", name: "Racing", icon: "🏎️", color: "from-orange-500/20 to-red-500/20" },
  { slug: "puzzle", name: "Puzzle", icon: "🧩", color: "from-sky-500/20 to-blue-500/20" },
  { slug: "strategy", name: "Strategy", icon: "🧠", color: "from-amber-500/20 to-yellow-500/20" },
  { slug: "sports", name: "Sports", icon: "⚽", color: "from-green-500/20 to-lime-500/20" },
  { slug: "simulation", name: "Simulation", icon: "🎯", color: "from-indigo-500/20 to-blue-500/20" },
  { slug: "indie", name: "Indie", icon: "🎮", color: "from-green-500/20 to-emerald-500/20" },
  { slug: "visual-novel", name: "Visual Novel", icon: "📖", color: "from-fuchsia-500/20 to-pink-500/20" },
  { slug: "survival", name: "Survival", icon: "🏕️", color: "from-emerald-500/20 to-teal-500/20" },
  { slug: "horror", name: "Horror", icon: "👻", color: "from-gray-500/20 to-red-500/20" },
  { slug: "building", name: "Building", icon: "🏗️", color: "from-yellow-500/20 to-amber-500/20" },
  { slug: "anime", name: "Anime", icon: "🎌", color: "from-pink-500/20 to-purple-500/20" },
];

export const PLATFORM_LABELS: Record<string, string> = {
  pc: "PC",
  ps1: "PlayStation 1",
  ps2: "PlayStation 2",
  ps3: "PlayStation 3",
  ps4: "PlayStation 4",
  ps5: "PlayStation 5",
  n64: "Nintendo 64",
  gamecube: "GameCube",
  wii: "Wii",
  wiiu: "Wii U",
  switch: "Nintendo Switch",
  genesis: "Sega Genesis",
  snes: "Super Nintendo",
  nes: "Nintendo",
  gb: "Game Boy",
  gba: "Game Boy Advance",
  ds: "Nintendo DS",
  "3ds": "Nintendo 3DS",
  xbox: "Xbox",
  xbox360: "Xbox 360",
  xboxone: "Xbox One",
  xboxseries: "Xbox Series",
};

export const HOME_CATEGORIES = CATEGORIES.slice(0, 12);
